@startuml

title __ENTORNO's Class Diagram__\n

      class edu.fiuba.algoChess.modelo.entorno.Celda {
          - piezaActual : Pieza
          - sectorDelJugador : Bando
          + eliminar()
          + guardarFaseInicial(Pieza):
          + guardarFaseJuego(Pieza):
          + obtenerBandoDePieza(): Bando
          + ubicar(Pieza):
      }

      class edu.fiuba.algoChess.modelo.entorno.CeldaNull {
      }

      class edu.fiuba.algoChess.modelo.entorno.DistanciaCercana {
          + ejecutarComportamientoPorDistancia(Pieza, Pieza):
      }

      class edu.fiuba.algoChess.modelo.entorno.DistanciaLejana {
          + ejecutarComportamientoPorDistancia(Pieza, Pieza):
      }

      class edu.fiuba.algoChess.modelo.entorno.DistanciaMedia {
          + ejecutarComportamientoPorDistancia(Pieza, Pieza):
      }

      class edu.fiuba.algoChess.modelo.entorno.DistanciaRelativa {
          {static} + calcularDistanciaRelativa(Ubicacion, Ubicacion)
          + ejecutarComportamientoPorDistancia()
      }

      class edu.fiuba.algoChess.modelo.entorno.ObservadorTablero {
          {static} - tablero : Tablero
          + obtenerCelda(Ubicacion): Celda
          + obtenerPieza(Ubicacion): Pieza
      }

      class edu.fiuba.algoChess.modelo.entorno.Tablero {
          - jugadorActivo : Jugador
          - campoDeBatalla : Map<Ubicacion, Celda>
          + asignarSectores(Bando, Bando):
          + eliminar(Ubicacion):
          + inicializarTablero(Bando, Bando):
          + ubicarEnCeldaFaseInicial(Pieza, Ubicacion):
          + ubicarEnCeldaFaseJuego(Pieza, Ubicacion):
          - inicializarObservadorTablero():
      }

      class edu.fiuba.algoChess.modelo.entorno.Ubicacion {
          - x : int
          - y : int
          - observador: ObservadorTablero
          + obtenerCelda(Ubicacion): Celda
          + obtenerPieza(Ubicacion): Pieza
          + reconocerTerrenoParaAtacarADistanciaMedia(Jinete, int, Ubicacion, Bando):
          - reconocerAliadoAXDistancia(Jinete, int, Ubicacion, Bando):
          - reconocerEnemigoAXDistancia(Jinete, int, Ubicacion, Bando):
      }

  edu.fiuba.algoChess.modelo.entorno.CeldaNull -up-|> edu.fiuba.algoChess.modelo.entorno.Celda
  edu.fiuba.algoChess.modelo.entorno.DistanciaCercana -up-|> edu.fiuba.algoChess.modelo.entorno.DistanciaRelativa
  edu.fiuba.algoChess.modelo.entorno.DistanciaLejana -up-|> edu.fiuba.algoChess.modelo.entorno.DistanciaRelativa
  edu.fiuba.algoChess.modelo.entorno.DistanciaMedia -up-|> edu.fiuba.algoChess.modelo.entorno.DistanciaRelativa


@enduml
